# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d10ba5c7d26add221cf13c0f84e3be98e2c96b7a59ae6ae0ed0ed54b9a76cc791bb76d21a48e96092720d2360d3d85dc855933ae99ba73d6d2ed7ef50f3e550

test:
  secret_key_base: 1dd2b1ed1f1c59f5b6d44a758fc7183d3eac5da54d71610ed978d3e22c1fbf30a1b9c5bf15baa492002237162a0e131b5f94e4e9995ae33481429fc47e56bee4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
